Fix grid snapping on all zoom levels
TAPAAL/tapaal-gui pull request #127
Opened 2023-12-14 13:35 UTC by NicEastvillage

Before, dragging objects at non-100% zoom would sometimes result in misaligned places, transitions, and arc points, which could never be aligned again. See [video of before](https://streamable.com/dr5oj6).

Now, objects always snap to the grid and align perfectly. See [video of now](https://streamable.com/hm76t5).

Resolved by making the `Grid::getModified` account for zoom level. Renamed it `Grid::align`.

2023-12-14 13:38 UTC, TheRumle approved these changes
Looks good to me 👍- it will solve many aesthetic frustrations

2023-12-14 20:32 UTC, srba requested changes
This break drawing arcs - zoom in, make a place and a transition above each other and then make an arc - sometimes the start of the arrow jumps to the side (and after rezooming this is fixed) and sometimes the arrow tip disappers inside of the transition (again after rezoom this is fixed).

2023-12-15 08:40 UTC, NicEastvillage commented
That happens on the main branch too and is a separate bug. But I can look into that too.

2023-12-15 10:18 UTC, NicEastvillage commented
I have fixed the issue. It is included in this PR.

2023-12-15 11:56 UTC, srba approved these changes
looks perfect!

2023-12-15 11:58 UTC, merged