Fixed annotation NPE
TAPAAL/tapaal-gui pull request #141
Opened 2024-02-28 12:42 UTC by mtygesen

Fixes NPE when creating a new annotation and trying to close it immediately.

2024-02-28 16:07 UTC, yrke commented on src/main/java/pipe/gui/petrinet/graphicElements/AnnotationNote.java
> -		guiDialog.addWindowListener(new WindowAdapter() {
is some other code making sure the annotation is not added to the net if you don't put in some text?

2024-02-28 16:31 UTC, yrke commented
I think you are right the code can be removed, but it will make it so two undo events are added to the stack when a new note is added: I suggest removed the snippet in this code + changing to something like the following: 

```` 
		if (!newText.equals(oldText) && !isFirstEdit) {
			// Text has been changed

			TAPAALGUI.getCurrentTab().getUndoManager().addNewEdit(
					new AnnotationTextEditCommand(this, oldText, newText)
			);
			updateBounds();
			return true;
		} else if (isFirstEdit && !newText.isBlank()) {
            return true;
        }
```
in function enableEditMode around line 200

2024-02-28 16:34 UTC, yrke requested changes
se commend above

2024-02-28 23:20 UTC, mtygesen commented
The redo/undo stack should now be working correctly

2024-02-29 14:08 UTC, yrke approved these changes

2024-03-07 16:26 UTC, srba approved these changes
tested and works fine

2024-03-07 16:27 UTC, merged